[package]
name = "project-file-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
thiserror = "1.0.47"
handler = { version = "*", path = "../handler" }
serde = { version = "1.0.183", features = ["derive"] }
toml = "0.7.6"
